workspace:
  base: /go
  path: src/github.com/ryan-s/drone-tutorial

pipeline:
  build:
    image: ${IMAGE}
    commands:
      - go build
      - go test

matrix:
  IMAGE:
    - golang:1.7
    - golang:1.8
    - golang:latest