FROM alpine:latest

RUN apk add --update curl python py-pip ca-certificates && \
    pip install --upgrade pip && \
    pip install httpie httpie-unixsocket && \
    rm -rf /var/cache/apk/*

WORKDIR /app

ENV SUT_TARGET undefined

ADD script/container-integ-test.sh /app/test.sh

CMD ["sh", "test.sh"]
